### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/linuxchixin#15]
Presently, the UI of Footer isn't good.
Make it look better; follow the theme.
Ask if you need help :)

**Comment by ShubhamKarala** [comment]
i will take it

**Comment by utkarsh2102** [comment]
Sure, please make a PR for the same.
Also, make sure change the branch first ;)
And only make a single commit.
The color of the footer should go with the theme.
And we need something like this:
![Sample](https://user-images.githubusercontent.com/31288318/49692693-b96e4080-fb86-11e8-9073-73148de4fd1e.png)
Just change the color as per the theme and add appropriate links and names.

**Comment by utkarsh2102** [comment]
Fixed via #20.
