### ISSUE TITLE
Add a page for COC.

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/linuxchixin#3]
There should be a page for Code Of Conduct.
For the content, refer to [IRC Etiquette](https://archive.linuxchix.org/irc-etiquette.html) and [LCA](http://linuxchixar.org/coc/).

**Comment by ironbatshashank** [comment]
I am working on this issue #3

**Comment by utkarsh2102** [comment]
Closing as the purpose of the repository has been changed.
