### ISSUE TITLE
Add a "About Us" section in "Delhi" page.

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/linuxchixin#6]
This is to be done after https://github.com/utkarsh2102/linuxchixin/issues/4 is resolved.
Inside the `Delhi` page, add an `About Us` section, specifically for the present LCI community.
Add a general content about the community. Ask if any help is needed.

**Comment by avinashkr1612** [comment]
I am working on this section...

**Comment by utkarsh2102** [comment]
Closing as the purpose of the repository has been changed.
