### ISSUE TITLE
Add a "Contact Us" section in "Delhi" page.

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/linuxchixin#9]
This is to be done after https://github.com/utkarsh2102/linuxchixin/issues/4 is resolved.
Inside the `Delhi` page, add a `Contact Us` section, specifically for the present LCI community.
Add general content about the community, like [GitHub](https://github.com/linuxchixin), [Twitter](https://twitter.com/linuxchixin/) and [Facebook](https://www.facebook.com/linuxchixin). Ask if any help is needed.

**Comment by cocoa1231** [comment]
Add two more links. One to [subscribe to the mailing list](http://mailman.linuxchix.org/mailman/listinfo/indichix) and another to [send a mail to the mailing list](mailto:indichix@linuxchix.org)

**Comment by avinashkr1612** [comment]
I am working on this issue #9

**Comment by utkarsh2102** [comment]
Closing as the purpose of the repository has been changed.
